### ISSUE TITLE
lapack.dppsv returned 1

### ISSUE THREAD

**Issue by starrysl** [anabranch/simple-spark-regression#1]
hi. Thank you for the tutorial. When I ran the example and I got the following error:

Exception in thread "main" java.lang.AssertionError: assertion failed: lapack.dppsv returned 1.
    at scala.Predef$.assert(Predef.scala:179)
    at org.apache.spark.mllib.linalg.CholeskyDecomposition$.solve(CholeskyDecomposition.scala:40)
    at org.apache.spark.ml.optim.WeightedLeastSquares.fit(WeightedLeastSquares.scala:117)

I tried on local mode and cluster mode on EC2, but the problem persists. May I ask what is the possible cause?

**Comment by bllchmbrs** [comment]
It looks like something in in lapack. If you take a look at the source code for Cholesky you'll see that it throws that error when the call to the linear algebra library fails. This has nothing to do with this repository (or spark) it's your environment's setup unfortunately.

I'd recommend registering for http://go.databricks.com/databricks-community-edition-beta-waitlist
it makes it a lot easier to run Spark.
